networks:
  iannunes-network:
    name: iannunes-network

services:
  rabbit-mq:
    image: rabbitmq:3.8.14-management
    container_name: rabbit-mq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - iannunes-network

  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    container_name: zipkin-server
    ports:
      - 9411:9411
    restart: always
    depends_on:
      - rabbit-mq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
    networks:
      - iannunes-network

  cambio-db:
    image: mysql:5.7.22
    container_name: cambio-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: cambio_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - iannunes-network
      
  book-db:
    image: mysql:5.7.22
    container_name: book-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: book_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3310
    ports:
      - 3310:3310
    expose:
      - 3310
    networks:
      - iannunes-network

  naming-server:
    image: iannunes/naming-server
    container_name: naming-server
    build:
      context: .
      dockerfile: 10-naming-server/Dockerfile
    volumes:
      - ./target:10-naming-server/target
    ports:
      - 8761:8761
    networks:
      - iannunes-network

  api-gateway:
    image: iannunes/api-gateway
    container_name: api-gateway
    build:
      context: .
      dockerfile: 10-api-gateway/Dockerfile
    volumes:
      - ./target:10-api-gateway/target
    ports:
      - 8765:8765
    depends_on:
      - naming-server
      - rabbit-mq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      MANAGEMENT.TRACING.SAMPLING.PROBABILITY: 1.0
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://localhost:9411/api/v2/spans
      RABBIT.URI: amqp://guest:guest@rabbit-mq:5672
      SPRING.ZIPKIN.SENDER.TYPE: rabbit
      SPRING.RABBITMQ.HOST: rabbit-mq
      SPRING.RABBITMQ.PORT: 5672
      SPRING.RABBITMQ.USERNAME: guest
      SPRING.RABBITMQ.PASSWORD: guest
      SPRING.APPLICATION.NAME: api-gateway
      SPRING.CLOUD.GATEWAY.DISCOVERY.LOCATOR.ENABLED: true
      SPRING.CLOUD.GATEWAY.ROUTES[0].ID: cambio-service
      SPRING.CLOUD.GATEWAY.ROUTES[0].URI: lb://cambio-service
      SPRING.CLOUD.GATEWAY.ROUTES[0].PREDICATES[0]: Path=/cambio-service/**
      SPRING.CLOUD.GATEWAY.ROUTES[1].ID: book-service
      SPRING.CLOUD.GATEWAY.ROUTES[1].URI: lb://book-service
      SPRING.CLOUD.GATEWAY.ROUTES[1].PREDICATES.0: Path=/book-service/**
      SPRING.CLOUD.GATEWAY.ROUTES[2].ID: openapi
      SPRING.CLOUD.GATEWAY.ROUTES[2].URI: lb://api-gateway
      SPRING.CLOUD.GATEWAY.ROUTES[2].PREDICATES[0]: Path=/v3/api-docs/**
      SPRING.CLOUD.GATEWAY.ROUTES[2].FILTERS[0]: RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
    networks:
      - iannunes-network

  cambio-service:
    image: iannunes/cambio-service
    container_name: cambio-service
    restart: always
    build:
      context: .
      dockerfile: 10-cambio-service/Dockerfile
    volumes:
      - ./target:10-cambio-service/target
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT.URI: amqp://guest:guest@rabbit-mq:5672
      SPRING.ZIPKIN.SENDER.TYPE: rabbit
      SPRING.RABBITMQ.HOST: rabbit-mq
      SPRING.RABBITMQ.PORT: 5672
      SPRING.RABBITMQ.USERNAME: guest
      SPRING.RABBITMQ.PASSWORD: guest
      SPRING.DATASOURCE.URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: docker
      SPRING.DATASOURCE.PASSWORD: admin123
      SPRING.FLYWAY.URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: admin123
    ports:
      - 8000:8000
    depends_on:
      - naming-server
      - cambio-db
      - rabbit-mq
    networks:
      - iannunes-network
      
  book-service:
    image: iannunes/book-service
    container_name: book-service
    restart: always
    build:
      context: .
      dockerfile: 10-book-service/Dockerfile
    volumes:
      - ./target:10-book-service/target
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT.URI: amqp://guest:guest@rabbit-mq:5672
      SPRING.ZIPKIN.SENDER.TYPE: rabbit
      SPRING.RABBITMQ.HOST: rabbit-mq
      SPRING.RABBITMQ.PORT: 5672
      SPRING.RABBITMQ.USERNAME: guest
      SPRING.RABBITMQ.PASSWORD: guest
      SPRING.DATASOURCE.URL: jdbc:mysql://book-db:3310/book_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: docker
      SPRING.DATASOURCE.PASSWORD: admin123
      SPRING.FLYWAY.URL: jdbc:mysql://book-db:3310/book_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: admin123
    ports:
      - 8100:8100
    depends_on:
      - naming-server
      - book-db
      - rabbit-mq
    networks:
      - iannunes-network